### ISSUE TITLE
Add privacy manifest per app store guidelines starting May 2024

### ISSUE THREAD

**Issue by RushanB** [starkdmi/MediaToolSwift#6]
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by starkdmi** [comment]
I found that there is no privacy accessed API used within the package. I placed `PrivacyInfo.xcprivacy` into the **Sources/** directory. @RushanB could you verify the issue with App Store Connect is resolved when using the **main** branch, so I can publish the release?

**Comment by starkdmi** [comment]
Well, finally generated Privacy Report in Xcode Organizer without any issue.
