### ISSUE TITLE
AudioTool error parsing duration

### ISSUE THREAD

**Issue by nbrandes** [starkdmi/MediaToolSwift#9]
I get an error on duration when trying to convert certain wav files.

`{ message: 'rpc error: code = Unknown desc = failed to crop video. ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers\n  built with gcc 13.2.1 (Alpine 13.2.1_git20231014) 20231014\n  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto=auto --enable-lv2 --enable-openssl --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl\n  libavutil      58. 29.100 / 58. 29.100\n  libavcodec     60. 31.102 / 60. 31.102\n  libavformat    60. 16.100 / 60. 16.100\n  libavdevice    60.  3.100 / 60.  3.100\n  libavfilter     9. 12.100 /  9. 12.100\n  libswscale      7.  5.100 /  7.  5.100\n  libswresample   5.  0.100 /  5.  0.100\n  libpostproc    57.  3.100 / 57.  3.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'/tmp/820186a7-98f3-4a62-a922-ebbb96a16f42_video_local.mp43513890586\':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 1\n    compatible_brands: isommp41mp42\n    creation_time   : 2024-11-21T09:53:33.000000Z\n  Duration: 00:00:59.76, start: 0.000000, bitrate: 483 kb/s\n  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 320 kb/s, 29.99 fps, 30 tbr, 15360 tbn (default)\n    Metadata:\n      creation_time   : 2024-11-21T09:53:33.000000Z\n      handler_name    : Core Media Video\n      vendor_id       : [0][0][0][0]\n  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)\n    Metadata:\n      creation_time   : 2024-11-21T09:53:33.000000Z\n      handler_name    : Core Media Audio\n      vendor_id       : [0][0][0][0]\nInvalid duration for option t: 00:01:118.629\nError parsing options for output file 820186a7-98f3-4a62-a922-ebbb96a16f42_crop.mp4.\nError opening output files: Invalid argument\n: exit status 234',`

Using these options:

AudioTool.convert(
                source: renderedUrl,
                destination: convertedUrl,
                fileType: .m4a,
                settings: .init(
                  codec: .aac,
                  bitrate: .value(128_000)
                ),
                skipSourceMetadata: true,
                copyExtendedFileMetadata: false,
                overwrite: true,
                deleteSourceFile: true,
                callback: { 
                }

**Comment by starkdmi** [comment]
@nbrandes, where did you get the logs from? MediaToolSwift is native library based on AVFoundation, but your logs show ffmpeg related info. Could you please provide steps, command and if possible a video file? Your Swift code seems OK to me.

**Comment by nbrandes** [comment]
Sorry about that, you are right this error is occuring in our backend not in MediaTool
